services:
  web:
    build: .
    ports:
      - "8029:8029"
    environment:
      - NODE_ENV=development
    volumes:
      # Mount source code for development (excluding node_modules)
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    # Increase shared memory for Chrome
    shm_size: 1gb
    # Security options for Chrome in container
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8029/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s